#
# Makefile for the Espresso ESP8089 wireless driver
#

obj-$(CONFIG_ESP8089) += esp_debug.o sdio_sif_esp.o spi_sif_esp.o esp_io.o \
			 esp_file.o esp_main.o esp_sip.o esp_ext.o esp_ctrl.o \
			 esp_mac80211.o esp_debug.o esp_utils.o esp_pm.o testmode.o
